# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: "SteelyardCore CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  macOS:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - xcode: latest
            runsOn: macos-13
            name: "macOS 13, Xcode latest"
          - xcode: latest-stable
            runsOn: macos-13
            name: "macOS 13, Xcode latest-stable"
          - xcode: "15.0"
            runsOn: macos-13
            name: "macOS 13, Xcode 15.0, Swift 5.9.0"
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }}  
      - name: ${{ matrix.name }}
        run: swift build -v
  iOS:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.runsOn }}
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        include:
          - destination: "OS=17.0,name=iPhone 14 Pro"
            name: "iOS 17.0"
            xcode: "15.0"
            runsOn: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode }} 
      - name: ${{ matrix.name }}
        run: xcodebuild clean build -scheme "SteelyardCore-Package" -destination "${{ matrix.destination }}" | xcpretty
